### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by KaungNyiSett** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#10]
In the starter code, in the Project tab, "app > test" and "app > androidTest" don't exist. It will be hard for beginners like me to create these folders myself. It will be better if these folders are already included in the starter code or you guys show how to create them in the codelab.

**Comment by osuleymanova** [comment]
Hello @KaungNyiSett,

Thank you for reaching out to us and sharing your concern. In order to help you with troubleshooting, please provide the screenshot of the issue.
Be sure that you are in Project pane:

![Screenshot 2023-01-30 at 12 08 30 PM](https://user-images.githubusercontent.com/86437155/215587640-3bb7e172-a0fa-48b6-8101-904b0104d57f.png)

**Comment by osuleymanova** [comment]
Closing this issue, since there is no response.
